spring.application.name=fiveg
spring.datasource.url=jdbc:mysql://localhost:3306/FinalProject
spring.datasource.username=root
spring.datasource.password=kirtiairtel
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080

spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis

spring.data.elasticsearch.cluster-name=elasticsearch_B0330878
spring.data.elasticsearch.cluster-nodes=localhost:9200
spring.data.elasticsearch.repositories.enabled=true
spring.main.allow-bean-definition-overriding=true
